/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DIS"
      | "MAN"
      | "MedicineStock"
      | "Owner"
      | "RET"
      | "addDistributor"
      | "addManufacturer"
      | "addMedicine"
      | "addRetailer"
      | "disAddressToId"
      | "disCtr"
      | "getDistributor"
      | "getDistributorCount"
      | "getManufacturer"
      | "getManufacturerCount"
      | "getMedicine"
      | "getMedicineCount"
      | "getMedicineStage"
      | "getRetailer"
      | "getRetailerCount"
      | "getRole"
      | "isDistributor"
      | "isManufacturer"
      | "isRetailer"
      | "manAddressToId"
      | "manCtr"
      | "medicineCtr"
      | "pack"
      | "receiveByDistributor"
      | "receiveByRetailer"
      | "retAddressToId"
      | "retCtr"
      | "sell"
      | "shipToDistributor"
      | "shipToRetailer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MedicineCreated"
      | "ParticipantRegistered"
      | "StageUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "DIS", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "MAN", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "MedicineStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "Owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "RET", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addMedicine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRetailer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disAddressToId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "disCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDistributor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistributorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getManufacturer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getManufacturerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMedicine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMedicineCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMedicineStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRetailer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRetailerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRetailer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manAddressToId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "manCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "medicineCtr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pack", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "receiveByDistributor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveByRetailer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retAddressToId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "retCtr", values?: undefined): string;
  encodeFunctionData(functionFragment: "sell", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "shipToDistributor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shipToRetailer",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "DIS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MedicineStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMedicine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disAddressToId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistributorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManufacturerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMedicine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMedicineCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMedicineStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRetailerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRetailer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manAddressToId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "medicineCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveByDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveByRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retAddressToId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "retCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shipToDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shipToRetailer",
    data: BytesLike
  ): Result;
}

export namespace MedicineCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    manufacturer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    manufacturer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    manufacturer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantRegisteredEvent {
  export type InputTuple = [
    role: string,
    participant: AddressLike,
    id: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    role: string,
    participant: string,
    id: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    role: string;
    participant: string;
    id: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StageUpdatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    stage: BigNumberish,
    updatedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    stage: bigint,
    updatedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    stage: bigint;
    updatedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DIS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  MAN: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  MedicineStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        manufacturer: string;
        distributor: string;
        retailer: string;
        stage: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
      }
    ],
    "view"
  >;

  Owner: TypedContractMethod<[], [string], "view">;

  RET: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  addDistributor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addMedicine: TypedContractMethod<[], [bigint], "nonpayable">;

  addRetailer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  disAddressToId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  disCtr: TypedContractMethod<[], [bigint], "view">;

  getDistributor: TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  getDistributorCount: TypedContractMethod<[], [bigint], "view">;

  getManufacturer: TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  getManufacturerCount: TypedContractMethod<[], [bigint], "view">;

  getMedicine: TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        manufacturer: string;
        distributor: string;
        retailer: string;
        stage: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
      }
    ],
    "view"
  >;

  getMedicineCount: TypedContractMethod<[], [bigint], "view">;

  getMedicineStage: TypedContractMethod<[_id: BigNumberish], [bigint], "view">;

  getRetailer: TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  getRetailerCount: TypedContractMethod<[], [bigint], "view">;

  getRole: TypedContractMethod<[_addr: AddressLike], [string], "view">;

  isDistributor: TypedContractMethod<[_addr: AddressLike], [boolean], "view">;

  isManufacturer: TypedContractMethod<[_addr: AddressLike], [boolean], "view">;

  isRetailer: TypedContractMethod<[_addr: AddressLike], [boolean], "view">;

  manAddressToId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  manCtr: TypedContractMethod<[], [bigint], "view">;

  medicineCtr: TypedContractMethod<[], [bigint], "view">;

  pack: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  receiveByDistributor: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  receiveByRetailer: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  retAddressToId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  retCtr: TypedContractMethod<[], [bigint], "view">;

  sell: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  shipToDistributor: TypedContractMethod<
    [_id: BigNumberish, _distributorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  shipToRetailer: TypedContractMethod<
    [_id: BigNumberish, _retailerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DIS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "MAN"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "MedicineStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        manufacturer: string;
        distributor: string;
        retailer: string;
        stage: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RET"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMedicine"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "addRetailer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disAddressToId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "disCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDistributor"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDistributorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getManufacturer"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getManufacturerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMedicine"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        manufacturer: string;
        distributor: string;
        retailer: string;
        stage: bigint;
        createdAt: bigint;
        updatedAt: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMedicineCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMedicineStage"
  ): TypedContractMethod<[_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRetailer"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRetailerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<[_addr: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<[_addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManufacturer"
  ): TypedContractMethod<[_addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRetailer"
  ): TypedContractMethod<[_addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manAddressToId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "manCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "medicineCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pack"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "receiveByDistributor"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "receiveByRetailer"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "retAddressToId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "retCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shipToDistributor"
  ): TypedContractMethod<
    [_id: BigNumberish, _distributorId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shipToRetailer"
  ): TypedContractMethod<
    [_id: BigNumberish, _retailerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MedicineCreated"
  ): TypedContractEvent<
    MedicineCreatedEvent.InputTuple,
    MedicineCreatedEvent.OutputTuple,
    MedicineCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantRegistered"
  ): TypedContractEvent<
    ParticipantRegisteredEvent.InputTuple,
    ParticipantRegisteredEvent.OutputTuple,
    ParticipantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StageUpdated"
  ): TypedContractEvent<
    StageUpdatedEvent.InputTuple,
    StageUpdatedEvent.OutputTuple,
    StageUpdatedEvent.OutputObject
  >;

  filters: {
    "MedicineCreated(uint256,address,uint256)": TypedContractEvent<
      MedicineCreatedEvent.InputTuple,
      MedicineCreatedEvent.OutputTuple,
      MedicineCreatedEvent.OutputObject
    >;
    MedicineCreated: TypedContractEvent<
      MedicineCreatedEvent.InputTuple,
      MedicineCreatedEvent.OutputTuple,
      MedicineCreatedEvent.OutputObject
    >;

    "ParticipantRegistered(string,address,uint256,uint256)": TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;
    ParticipantRegistered: TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;

    "StageUpdated(uint256,uint8,address,uint256)": TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;
    StageUpdated: TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;
  };
}
